export const ALL_ARTICLES_REQUEST = 'ALL_ARTICLES_REQUEST';
export const ALL_ARTICLES_SUCCESS = 'ALL_ARTICLES_SUCCESS';
export const ALL_ARTICLES_FAIL = 'ALL_ARTICLES_FAIL';
export const SINGLE_ARTICLE_REQUEST = 'SINGLE_ARTICLE_REQUEST';
export const SINGLE_ARTICLE_SUCCESS = 'SINGLE_ARTICLE_SUCCESS';
export const SINGLE_ARTICLE_FAIL = 'SINGLE_ARTICLE_FAIL';