export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';
export const CREATE_ARTICLE_SHOW_SUCCESS_MESSAGE = 'CREATE_ARTICLE_SHOW_SUCCESS_MESSAGE';
export const CREATE_ARTICLE_HIDE_SUCCESS_MESSAGE = 'CREATE_ARTICLE_HIDE_SUCCESS_MESSAGE';
export const CREATE_ARTICLE_SHOW_ERROR_MESSAGE = 'CREATE_ARTICLE_SHOW_ERROR_MESSAGE';
export const CREATE_ARTICLE_HIDE_ERROR_MESSAGE = 'CREATE_ARTICLE_HIDE_ERROR_MESSAGE';
