export const LOGIN_CHANGE_LOGIN = 'LOGIN_CHANGE_LOGIN';
export const LOGIN_CHANGE_PASS = 'LOGIN_CHANGE_PASS';
export const LOGIN_DATA_REQUEST = 'LOGIN_DATA_REQUEST';
export const LOGIN_DATA_SUCCESS = 'LOGIN_DATA_SUCCESS';
export const LOGIN_DATA_FAIL = 'LOGIN_DATA_FAIL';
export const LOGIN_AUTH_CONNECT = 'LOGIN_AUTH_CONNECT';
export const LOGIN_AUTH_DISCONNECT = 'LOGIN_AUTH_DISCONNECT';