export const REGISTER_CHANGE_LOGIN = 'REGISTER_CHANGE_LOGIN';
export const REGISTER_CHANGE_PASS = 'REGISTER_CHANGE_PASS';
export const REGISTER_DATA_REQUEST = 'REGISTER_DATA_REQUEST';
export const REGISTER_DATA_SUCCESS = 'REGISTER_DATA_SUCCESS';
export const REGISTER_DATA_FAIL = 'REGISTER_DATA_FAIL';