export const SOCKET_DATA_RECEIVE = 'SOCKET_DATA_RECEIVE';
export const SOCKET_DATA_SEND = 'SOCKET_DATA_SEND';
export const SOCKET_DATA_ERROR = 'SOCKET_DATA_ERROR';
export const SOCKET_MESSAGES_REQUEST = 'SOCKET_MESSAGES_REQUEST';
export const SOCKET_MESSAGES_SUCCESS = 'SOCKET_MESSAGES_SUCCESS';
export const SOCKET_MESSAGES_ERROR = 'SOCKET_MESSAGES_ERROR';